PROG6-2016-Tamagotchi/Models/Tamagotchi.cs
using PROG6_2016_Tamagotchi.Models.Action;
using PROG6_2016_Tamagotchi.Models.GameRule;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PROG6_2016_Tamagotchi.Models
{
    public class Tamagotchi
    {
        private static Random random = new Random();

        [Key]
        public int Id { get; set; }

        public String Name { get; set; }

        public int Cooldown { get; set; }

        public DateTime LastAccess { get; set; }

        public DateTime Created { get; set; }

        public int Age { get; set; }

        public int Hunger { get; set; }

        public int Sleep { get; set; }

        public int Bored { get; set; }

        public int Health { get; set; }

        private Tiredness tiredness = new Tiredness();
        private Boredom boredom = new Boredom();
        private Hunger hunger = new Hunger();

        private HugAction feed = new HugAction();
        private SleepAction sleepA = new SleepAction();
        private PlayAction play = new PlayAction();
        private HugAction hug = new HugAction();

        public void UpdateStatus()
        {
            Sleep = tiredness.ExecuteGameRule(this, random.Next(15, 35)).Sleep;
            Bored = boredom.ExecuteGameRule(this, random.Next(15, 35)).Bored;
            Hunger = hunger.ExecuteGameRule(this, random.Next(15, 35)).Hunger;

            if (Health > 0)
            {
                TimeSpan deltaTime = DateTime.UtcNow - LastAccess;
                Age += deltaTime.Seconds;
            }

            if (Cooldown > 0)
            {
                TimeSpan deltaTime = DateTime.UtcNow - LastAccess;

                if (Cooldown - deltaTime.Seconds < 0)
                {
                    Cooldown = 0;
                }
                else
                {
                    Cooldown -= deltaTime.Seconds;
                }
            }

            LastAccess = DateTime.UtcNow;
        }

        public void Feed()
        {
            feed.ExectuteAction(this);
        }

        public void SleepA()
        {
            sleepA.ExectuteAction(this);
        }

        public void Play()
        {
            play.ExectuteAction(this);
        }

        public void Hug()
        {
            hug.ExectuteAction(this);
        }
    }
}

PROG6-2016-Tamagotchi/Controllers/TamagotchisController.cs
using PROG6_2016_Tamagotchi.Models;
using PROG6_2016_Tamagotchi.Models.GameRule;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PROG6_2016_Tamagotchi.Controllers
{
    public class TamagotchisController : Controller
    {
        private Models.Database db = new Models.Database();

        // GET: Tamagotchi
        public ActionResult Index()
        {
            return View(db.Tamagotchis.ToList());
        }

        // GET: Tamagotchi/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tamagotchi tamagotchi = db.Tamagotchis.Find(id);
            if (tamagotchi == null)
            {
                return HttpNotFound();
            }

            tamagotchi.UpdateStatus();
            db.SaveChanges();

            return View(tamagotchi);
        }

        // GET: Tamagotchi/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: Tamagotchi/CreateMultiple
        public ActionResult CreateMultiple()
        {
            return View();
        }

        // POST: Tamagotchi/CreateMultiple
        [HttpPost]
        public ActionResult CreateMultiple(FormCollection form)
        {
            int amount = Int32.Parse(form["Amount"]);

            for (int i = amount; i > 0; i--)
            {
                db.Tamagotchis.Add(new Tamagotchi() { Name = "New Tamagotchi #" + (amount - i), Created = DateTime.UtcNow, LastAccess = DateTime.UtcNow, Health = 100 });
            }

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: Tamagotchi/Refresh
        public ActionResult Refresh()
        {
            foreach (Tamagotchi tamagotchi in db.Tamagotchis)
            {
                tamagotchi.UpdateStatus();
            }

            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // POST: Tamagotchi/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,LastAccess,Created,Age,Hunger,Sleep,Bored,Health")] Tamagotchi tamagotchi)
        {
            tamagotchi.Created = DateTime.UtcNow;
            tamagotchi.LastAccess = DateTime.UtcNow;
            tamagotchi.Health = 100;

            if (ModelState.IsValid)
            {
                db.Tamagotchis.Add(tamagotchi);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tamagotchi);
        }

        // POST: Tamagotchi/Details
        [HttpPost]
        public ActionResult Details(int? id, FormCollection form)
        {
            var tamagotchi = db.Tamagotchis.Where(x => x.Id == id).First();
            string action = form["Action"].ToString();

            if (tamagotchi.Cooldown == 0 &&
                tamagotchi.Health != 0)
            {
                if (action.Equals("Feed"))
                {
                    tamagotchi.Feed();
                }
                else if (action.Equals("Sleep"))
                {
                    tamagotchi.SleepA();
                }
                else if (action.Equals("Play"))
                {
                    tamagotchi.Play();
                }
                else if (action.Equals("Hug"))
                {
                    tamagotchi.Hug();
                }
            }

            tamagotchi.UpdateStatus();
            db.SaveChanges();
            return RedirectToAction("Details", id);

            //return RedirectToAction("Wait", selectedTamagotchi);
        }

        // GET: Tamagotchi/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tamagotchi tamagotchi = db.Tamagotchis.Find(id);
            if (tamagotchi == null)
            {
                return HttpNotFound();
            }

            tamagotchi.UpdateStatus();
            db.SaveChanges();

            return View(tamagotchi);
        }

        // POST: Tamagotchi/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,LastAccess,Created,Age,Hunger,Sleep,Bored,Health")] Tamagotchi tamagotchi)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tamagotchi).State = EntityState.Modified;
                tamagotchi.UpdateStatus();
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tamagotchi);
        }

        // GET: Tamagotchi/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tamagotchi tamagotchi = db.Tamagotchis.Find(id);
            if (tamagotchi == null)
            {
                return HttpNotFound();
            }

            tamagotchi.UpdateStatus();
            db.SaveChanges();

            return View(tamagotchi);
        }

        // POST: Tamagotchi/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tamagotchi tamagotchi = db.Tamagotchis.Find(id);
            db.Tamagotchis.Remove(tamagotchi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PROG6-2016-Tamagotchi/Views/Tamagotchis/Create.cshtml
@model PROG6_2016_Tamagotchi.Models.Tamagotchi

@{
    ViewBag.Title = "Create";
}

<link type="text/css" rel="stylesheet" href="~/Content/Site.css" />


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <p>

    </p>
    <div class="form-horizontal" style="background-color: #d5ddea; padding: 10px; border-radius: 4px;">
        <h4>Create Tamagotchi</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group"  style="padding: 20px;">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}
<p>

</p>

<ul class="CreatureList" style="padding: 10px; width: 1100px;">
    <li class="Creatures">
            <img src="~/Resources/Tamagotchi1.png" alt="Tamagotchi1" height="90" width="90" >
            <input type="radio"/>
    </li>
    <li class="Creatures">
        <img src="~/Resources/Tamagotchi2.png" alt="Tamagotchi2"  height="90" width="90">
        <input type="radio" />
    </li>
    <li class="Creatures">
        <img src="~/Resources/Tamagotchi3.png" alt="Tamagotchi3"  height="90" width="90">
        <input type="radio" />
    </li>
    <li class="Creatures">
        <img src="~/Resources/Tamagotchi4.png" alt="Tamagotchi4"  height="90" width="90">
        <input type="radio" />
    </li>
    <li class="Creatures">
        <img src="~/Resources/Tamagotchi5.png" alt="Tamagotchi5"  height="90" width="90">
        <input type="radio" />
    </li>
    <li class="Creatures">
        <img src="~/Resources/Tamagotchi11.png" alt="Tamagotchi11"  height="90" width="90">
        <input type="radio" />
    </li>
    <li class="Creatures">
        <img src="~/Resources/Tamagotchi12.png" alt="Tamagotchi12"  height="90" width="90">
        <input type="radio" />
    </li>
</ul>
<p>

</p>

<ul class="CreatureList" style="padding: 10px; width: 1100px;">
    <li class="Creatures">
        <img src="~/Resources/Tamagotchi6.png" alt="Tamagotchi6"  height="90" width="90">
        <input type="radio" />
    </li>
    <li class="Creatures">
        <img src="~/Resources/Tamagotchi7.png" alt="Tamagotchi7"  height="90" width="90">
        <input type="radio" />
    </li>
    <li class="Creatures">
        <img src="~/Resources/Tamagotchi13.png" alt="Tamagotchi13"  height="90" width="90">
        <input type="radio" />
    </li>
    <li class="Creatures">
        <img src="~/Resources/Tamagotchi8.png" alt="Tamagotchi8"  height="90" width="90">
        <input type="radio" />
    </li>
    <li class="Creatures">
        <img src="~/Resources/Tamagotchi10.png" alt="Tamagotchi10"  height="90" width="90">
        <input type="radio" />
    </li>
    <li class="Creatures">
        <img src="~/Resources/Tamagotchi14.png" alt="Tamagotchi14"  height="90" width="90">
        <input type="radio" />
    </li>
    <li class="Creatures">
        <img src="~/Resources/Tamagotchi9.png" alt="Tamagotchi9"  height="90" width="90">
        <input type="radio" />
    </li>
 </ul>

<div style="background-color: #d5ddea; padding: 10px;">
   <label>
       Press enter to create your Tamagotchi
   </label>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PROG6-2016-Tamagotchi/Views/Tamagotchis/CreateMultiple.cshtml

@{
    ViewBag.Title = "CreateMultiple";
}

<h2 style="background-color: #d5ddea; padding:10px;">Create multiple</h2>

<form method="post">
    <div class="form-horizontal"  style="background-color: #d5ddea; padding:10px;">
        <div>
            <label  style="background-color: #d5ddea; padding:10px;">Amount</label>
            @Html.TextBox("Amount", null, new { @class = "span1", type = "number", required = "required", min = 1, max = 100 })
        </div>
        <div class="form-group">
            <label>&nbsp;</label>
            <button value="CreateMultiple" type="submit"
                    class="btn btn-success">
                Create
            </button>
        </div>
    </div>
</form>

<div  style="background-color: #d5ddea; padding:10px;">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PROG6-2016-Tamagotchi/Views/Tamagotchis/Delete.cshtml
@model PROG6_2016_Tamagotchi.Models.Tamagotchi

@{
    ViewBag.Title = "Delete";
}

<h2 style="background-color: #d5ddea; padding: 10px; border-radius: 4px;">Delete</h2>

<h3 style="background-color: #d5ddea; padding: 10px; border-radius: 4px;">Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal" style="background-color: #d5ddea; padding:10px; border-radius: 4px;">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hunger)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.Hunger)*@
            <div class="progress-bar" role="progressbar" aria-valuenow="@Html.DisplayFor(model => model.Hunger)" aria-valuemin="0" aria-valuemax="100" style="width:@Html.DisplayFor(model => model.Hunger)%; background-color:#ceb388;">
                @Html.DisplayFor(model => model.Hunger)%
            </div>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sleep)
        </dt>

        <dd>
            <div class="progress-bar" role="progressbar" aria-valuenow="@Html.DisplayFor(model => model.Sleep)" aria-valuemin="0" aria-valuemax="100" style="width:@Html.DisplayFor(model => model.Sleep)%; background-color:#88c2ce;">
                @Html.DisplayFor(model => model.Sleep)%
            </div>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bored)
        </dt>

        <dd>
            <div class="progress-bar" role="progressbar" aria-valuenow="@Html.DisplayFor(model => model.Bored)" aria-valuemin="0" aria-valuemax="100" style="width:@Html.DisplayFor(model => model.Bored)%; background-color:#db8585;">
                @Html.DisplayFor(model => model.Bored)%
            </div>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Health)
        </dt>

        <dd>
            <div class="progress-bar" role="progressbar" aria-valuenow="@Html.DisplayFor(model => model.Health)" aria-valuemin="0" aria-valuemax="100" style="width:@Html.DisplayFor(model => model.Health)%; background-color:#8fe093;">
                @Html.DisplayFor(model => model.Health)%
            </div>
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="background-color: #d5ddea; padding: 10px; border-radius: 4px;">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PROG6-2016-Tamagotchi/Views/Tamagotchis/Details.cshtml
@model PROG6_2016_Tamagotchi.Models.Tamagotchi

@{
    ViewBag.Title = "Details";
}

<link type="text/css" rel="stylesheet" href="~/Content/Site.css" />
<h2 style="background-color: #d5ddea; padding:10px; border-radius: 4px;">Details</h2>

<div>
    <h4 style="background-color: #d5ddea; padding:10px; border-radius: 4px;"> Your Tamagotchi</h4>
    <hr />
    <dl style="background-color: #d5ddea; padding:10px; border-radius: 4px;" class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)

        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Hunger)
        </dt>

        <dd>
            <div class="progress-bar" role="progressbar" aria-valuenow="@Html.DisplayFor(model => model.Hunger)" aria-valuemin="0" aria-valuemax="100" style="width:@Html.DisplayFor(model => model.Hunger)%; background-color:#ceb388;">
                @Html.DisplayFor(model => model.Hunger)%
            </div>
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Sleep)
        </dt>

        <dd>
            <div class="progress-bar" role="progressbar" aria-valuenow="@Html.DisplayFor(model => model.Sleep)" aria-valuemin="0" aria-valuemax="100" style="width:@Html.DisplayFor(model => model.Sleep)%; background-color:#88c2ce;">
                @Html.DisplayFor(model => model.Sleep)%
            </div>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bored)
        </dt>

        <dd>
            <div class="progress-bar" role="progressbar" aria-valuenow="@Html.DisplayFor(model => model.Bored)" aria-valuemin="0" aria-valuemax="100" style="width:@Html.DisplayFor(model => model.Bored)%; background-color:#db8585;">
                @Html.DisplayFor(model => model.Bored)%
            </div>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Health)
        </dt>

        <dd>
            <div class="progress-bar" role="progressbar" aria-valuenow="@Html.DisplayFor(model => model.Health)" aria-valuemin="0" aria-valuemax="100" style="width:@Html.DisplayFor(model => model.Health)%; background-color:#8fe093;">
                @Html.DisplayFor(model => model.Health)%
            </div>
        </dd>
    </dl>

</div>

<div style="background-color: #d5ddea; border-radius: 4px; padding: 10px;">
    <form method="post">
        <input type="submit" name="Action" value="Feed" onclick="location.href='@Url.Action("Details", "Tamagotchis")'"
               style="margin-left: 4px; background-color: #ffb15e; padding: 10px; border-radius: 4px;" />
        <input type="submit" name="Action" value="Sleep" onclick="location.href='@Url.Action("Details", "Tamagotchis")'"
               style="margin-left: 4px; background-color: #ffb15e; padding: 10px; border-radius: 4px;" />
        <input type="submit" name="Action" value="Play" onclick="location.href='@Url.Action("Details", "Tamagotchis")'"
               style="margin-left: 4px; background-color: #ffb15e; padding: 10px; border-radius: 4px;" />
        <input type="submit" name="Action" value="Hug" onclick="location.href='@Url.Action("Details", "Tamagotchis")'"
               style="margin-left: 4px; background-color: #ffb15e; padding: 10px; border-radius: 4px;" />
        @Html.ActionLink("Refresh All", "Details")
    </form>
    
    @if (Model.Cooldown > 0)
    {
        <p style="margin-top: 20px;">Cooldown: @Model.Cooldown seconds left</p>
    }
    else
    {
        <p style="margin-top: 20px;">Cooldown: No cooldown!</p>
    }
</div>

<p>

</p>

<p style="background-color: #d5ddea; padding:10px; border-radius: 4px; ">
    @Html.ActionLink("Delete", "Delete", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>



PROG6-2016-Tamagotchi/Views/Tamagotchis/Index.cshtml
@model IEnumerable<PROG6_2016_Tamagotchi.Models.Tamagotchi>

@{
    ViewBag.Title = "Tamagotchi's";
}
<link type="text/css" rel="stylesheet" href="~/Content/Site.css" />

<h2 style="background-color: #d5ddea; opacity: 1; padding: 10px; border-radius: 4px;">Select your Tamagotchi here</h2>


<p style="background-color: #d5ddea; opacity: 1; padding:5px; border-radius: 4px; ">
    @Html.ActionLink("Create a Tamagotchi", "Create") |
    @Html.ActionLink("Create multiple Tamagotchi", "CreateMultiple") |
    @Html.ActionLink("Refresh All", "Refresh")
</p>
<table class="table" style="background-color: #d5ddea; opacity: 0.9; border-radius: 4px;">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Hunger)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sleep)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Bored)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Health)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Hunger)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sleep)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bored)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Health)
        </td>
        <td>
            @Html.ActionLink("Next", "Details", new { id=item.Id }) 
        </td>
    </tr>
}
</table>